services:
  app:
    build:
      context: .
      args:
        NEXT_PUBLIC_KAKAO_MAP_KEY: ${NEXT_PUBLIC_KAKAO_MAP_KEY}
    container_name: momentree
    ports:
      - "3001:3000"
    volumes:
      - /data/momentree:/data/momentree
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
